import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'category', label: '首页', items: ['README']}],
  AcademicSidebar: [{type: 'autogenerated', dirName: 'academic-resources'}],
  GrowthSidebar: [{type: 'autogenerated', dirName: 'growth-path'}],

  HelpSidebar: [{type: 'autogenerated', dirName: 'Community-hub'}],

  LifeSidebar: [
    {
      type: 'category',
      label: '生活相关',
      items: [
        'Life/campus-life/FirstLesson-Of-School',
        'Life/campus-life/Different-Courses',
        'Life/campus-life/Signin-And-Attendance',
        'Life/campus-life/Changing-Majors',
        'Life/campus-life/Minor',
        'Life/campus-life/Student-Email',
        'Life/campus-life/Library',
        'Life/campus-life/Resolving-Conflicts',
        'Life/campus-life/Relation-Ships',
        'Life/campus-life/Getting-Out-Of-Singleness',
        'Life/campus-life/Medical-Insurance',
        'Life/campus-life/International-Exchange',
        'Life/campus-life/national-student-loan-FAQ',
      ],
    },
    {
      type: 'category',
      label: '圆梦帮扶',
      items: [
        'Life/Dream-Realization-Assistance/Scholar-Ship',
        'Life/Dream-Realization-Assistance/Work-Study-Program',
        // 你可以继续补充其它 Dream-Realization-Assistance 相关文档
      ],
    },
  ],

  repositorySidebar: [
    {
      type: 'category',
      label: '计算机技术',
      items: [
        // SurfingTutorial 总览
        'Computer/computer-basic/SurfingTutorial',
        // 自动生成 SurfingTutorial 下的各章节
        {
          type: 'autogenerated',
          dirName: 'Computer/computer-basic/SurfingTutorial/chap2',
        },
        {
          type: 'autogenerated',
          dirName: 'Computer/computer-basic/SurfingTutorial/chap3',
        },
        {
          type: 'autogenerated',
          dirName: 'Computer/computer-basic/SurfingTutorial/chap4',
        },
      ],
    },
    // 你可以继续补充其它 Computer 相关内容
    {
      type: 'category',
      label: '通用技能',
      items: [
        'Computer/general-skills/search-platforms',
        'Computer/general-skills/student-discounts',
      ],
    },
    {
      type: 'category',
      label: '效率工具',
      items: [
        'Computer/tools/tools',
      ],
    },
  ],
};

export default sidebars;
